spring:
  application:
    name: bff-todolist

  datasource:
    url: jdbc:postgresql://localhost:5432/todolists_db
    username: postgres
    password: password # very secure password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

application:
  front-url: http://localhost:3000
  security:
    password-encoder:
      strength: 10
      secret: SuperSecretKey