DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS TODOLIST;
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS USER_ACCOUNT;

CREATE TABLE IF NOT EXISTS USER_ACCOUNT (
  ID UUID PRIMARY KEY,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  ACCOUNT_DUE_TIME TIMESTAMP NOT NULL,
  ACCOUNT_NON_LOCKED BOOLEAN NOT NULL,
  CREDENTIALS_DUE_TIME TIMESTAMP NOT NULL,
  ENABLED BOOLEAN NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
  USER_ID UUID NOT NULL,
  ROLE VARCHAR(255) NOT NULL,
  PRIMARY KEY (USER_ID, ROLE),
  FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(ID)
);

CREATE TABLE IF NOT EXISTS TODOLIST (
  TODOLIST_ID UUID PRIMARY KEY,
  TODOLIST_TITLE VARCHAR(255) NOT NULL,
  TODOLIST_DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TASK (
  TASK_ID UUID PRIMARY KEY,
  TASK_TITLE VARCHAR(255) NOT NULL,
  TASK_DESCRIPTION VARCHAR(255) NOT NULL,
  TASK_CHECKED BOOLEAN NOT NULL,
  TASK_DUE_DATE TIMESTAMP,
  TODOLIST_ID UUID NOT NULL,
  FOREIGN KEY (TODOLIST_ID) REFERENCES TODOLIST(TODOLIST_ID)
);